### ISSUE TITLE
Upgrade guzzle to 7

### ISSUE THREAD

**Issue by m-a-k-o** [cardinity/cardinity-sdk-php#20]
Cardinity SDK requires guzzle 6.x although current version is 7.x. I've been using version 7.x because other packages require that specific version. I can't install cardinity-sdk-php because of composer's conflict between those two versions.

**Comment by atikhashmee** [comment]
Hey I was going to create an issue for the same reason. I am trying to install this package but due to same reason its not being installed. I guess, your update is not applied to master branch. could you guys do this? so that I can install this package ? 
![image](https://user-images.githubusercontent.com/26138112/109377989-497c3a00-78f9-11eb-85eb-351331e83d2b.png)

**Comment by encenta** [comment]
We have also stumbled on the same issue. Is there a plan to integrate the update for Guzzle 7 into the master branch? Thanks
